config/routes.rb
Battleship::Application.routes.draw do
  resources :users
  resources :games
  
  get "/start" => "games#create"
  get "/play"  => "pages#play"
  get "/logout" => "pages#logout"
  post "/proxy" => "pages#proxy"
  get "/fire/:row/:cell" => "games#update", as: "fire"

  root :to => 'pages#index'

end

app/views/pages/index.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name, "Name:" %><br/>
  <%= f.text_field :name %><br/>
  <br/>
  <%= f.label :email, "Email:" %><br/>
  <%= f.text_field :email %><br/>
  <br/>
  <%= f.submit "Play" %>
<% end %>

app/views/pages/play.html.erb
<div class="panel">
  <div class="user_info">
    <h2><%= current_user.name %></h2>
    <h4><%= current_user.email %></h4>
    <%= link_to "Edit", edit_user_path(current_user) %>
  </div>

  <div class="links">
    <%= link_to "New Game", start_path, class: "new_game #{@win_message ? "highlight" : ""}" %>&nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to "Logout", logout_path, class: :logout %>
  </div>
</div>

<% if @win_message %>
  <div class="win">
    <h1><%= @win_message %></h1>
  </div>
<% end %>

<div id="game_user" class="game">
  <h4>You</h4>
  <div class="board">
    <% @board_user.each do |row| %>
      <div class="row">
        <% row.each do |cell| %>
          <% if cell.hit? && !cell.ship? %>
            <div class="cell miss"></div>
          <% else %>
            <div class="cell">
              <% if cell.ship? %>
                <% if cell.hit? %>
                  <div class="ship <%= boat_classes(cell).join(' ') %> hit"></div>
                <% else %>
                  <div class="ship <%= boat_classes(cell).join(' ') %>"></div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <ul class="ships">
    <li class="carrier <%= @sunk_user.include?("Carrier") ? "sunk" : "" %>"><span>Carrier</span></li>
    <li class="battleship <%= @sunk_user.include?("Battleship") ? "sunk" : "" %>"><span>Battleship</span></li>
    <li class="destroyer <%= @sunk_user.include?("Destroyer") ? "sunk" : "" %>"><span>Destroyer</span></li>
    <li class="submarine <%= @sunk_user.include?("Submarine 1") ? "sunk" : "" %>"><span>Submarine</span></li>
    <li class="submarine <%= @sunk_user.include?("Submarine 2") ? "sunk" : "" %>"><span>Submarine</span></li>
    <li class="patrol <%= @sunk_user.include?("Patrol Boat 1") ? "sunk" : "" %>"><span>Patrol Boat</span></li>
    <li class="patrol <%= @sunk_user.include?("Patrol Boat 2") ? "sunk" : "" %>"><span>Patrol Boat</span></li>
  </ul>
</div>

<div id="game_comp" class="game">
  <h4>Opponent</h4>
  <div class="board">
    <% @board_comp.each_with_index do |row, row_i| %>
      <div class="row">
        <% row.each_with_index do |cell, cell_i| %>
          <% if cell.ship? && cell.hit? %>
            <div class="cell hit"></div>
          <% elsif cell.hit? %>
            <div class="cell miss"></div>
          <% else %>
            <a href="<%= fire_path row_i, cell_i %>" class="cell"></a>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <ul class="ships">
    <li class="carrier <%= @sunk_comp.include?("Carrier") ? "sunk" : "" %>"><span>Carrier</span></li>
    <li class="battleship <%= @sunk_comp.include?("Battleship") ? "sunk" : "" %>"><span>Battleship</span></li>
    <li class="destroyer <%= @sunk_comp.include?("Destroyer") ? "sunk" : "" %>"><span>Destroyer</span></li>
    <li class="submarine <%= @sunk_comp.include?("Submarine 1") ? "sunk" : "" %>"><span>Submarine</span></li>
    <li class="submarine <%= @sunk_comp.include?("Submarine 2") ? "sunk" : "" %>"><span>Submarine</span></li>
    <li class="patrol <%= @sunk_comp.include?("Patrol Boat 1") ? "sunk" : "" %>"><span>Patrol Boat</span></li>
    <li class="patrol <%= @sunk_comp.include?("Patrol Boat 2") ? "sunk" : "" %>"><span>Patrol Boat</span></li>
  </ul>
</div>